"""Contracts for future inspection semantic validation; no executor is wired."""

from app.services.inspection_validation.interfaces import (
    ArtifactIntegrityInspection,
    ArtifactTechnicalSummary,
    DimensionRelationship,
    FilesystemIntegrityInspector,
    FindingCategory,
    FindingSeverity,
    InspectionPairValidator,
    InspectionValidationPolicy,
    InspectionValidationResult,
    InspectionValidationStatusTransition,
    NativeFormatInspector,
    ReadabilityStatus,
    StoredArtifactReference,
    ValidationArtifactRetriever,
    ValidationFinding,
    ValidationOutcome,
    ValidationPolicyEvaluator,
    ValidationResultPersistence,
    ValidationSummary,
)

__all__ = [
    "ArtifactIntegrityInspection",
    "ArtifactTechnicalSummary",
    "DimensionRelationship",
    "FilesystemIntegrityInspector",
    "FindingCategory",
    "FindingSeverity",
    "InspectionPairValidator",
    "InspectionValidationPolicy",
    "InspectionValidationResult",
    "InspectionValidationStatusTransition",
    "NativeFormatInspector",
    "ReadabilityStatus",
    "StoredArtifactReference",
    "ValidationArtifactRetriever",
    "ValidationFinding",
    "ValidationOutcome",
    "ValidationPolicyEvaluator",
    "ValidationResultPersistence",
    "ValidationSummary",
]
