"""Authoritative persisted inspection audit action identifiers."""

INSPECTION_RECEIVED = "INSPECTION_RECEIVED"
INSPECTION_INTAKE_FAILED = "INSPECTION_INTAKE_FAILED"
INSPECTION_VALIDATION_PASSED = "INSPECTION_VALIDATION_PASSED"
INSPECTION_VALIDATION_FAILED = "INSPECTION_VALIDATION_FAILED"
INSPECTION_VALIDATION_ERROR = "INSPECTION_VALIDATION_ERROR"
INSPECTION_PROCESSING_STARTED = "INSPECTION_PROCESSING_STARTED"
INSPECTION_MOCK_RESULT_PASS = "INSPECTION_MOCK_RESULT_PASS"
INSPECTION_MOCK_RESULT_FAIL = "INSPECTION_MOCK_RESULT_FAIL"
INSPECTION_MOCK_RESULT_UNCERTAIN = "INSPECTION_MOCK_RESULT_UNCERTAIN"
INSPECTION_PROCESSING_ERROR = "INSPECTION_PROCESSING_ERROR"

VALIDATION_ACTIONS = frozenset(
    {
        INSPECTION_VALIDATION_PASSED,
        INSPECTION_VALIDATION_FAILED,
        INSPECTION_VALIDATION_ERROR,
    }
)
MOCK_RESULT_BY_ACTION = {
    INSPECTION_MOCK_RESULT_PASS: "PASS",
    INSPECTION_MOCK_RESULT_FAIL: "FAIL",
    INSPECTION_MOCK_RESULT_UNCERTAIN: "UNCERTAIN",
}
PROCESSING_ACTIONS = frozenset(
    {
        INSPECTION_PROCESSING_STARTED,
        INSPECTION_PROCESSING_ERROR,
        *MOCK_RESULT_BY_ACTION,
    }
)
