from enum import Enum


class ValidationOutcome(str, Enum):
    VALIDATION_PASSED = "VALIDATION_PASSED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATION_ERROR = "VALIDATION_ERROR"


class FindingSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class FindingCategory(str, Enum):
    PAIR = "PAIR"
    FILE_INTEGRITY = "FILE_INTEGRITY"
    FORMAT = "FORMAT"
    IMAGE_PROPERTIES = "IMAGE_PROPERTIES"
    HEIGHT_PROPERTIES = "HEIGHT_PROPERTIES"
    REGISTRATION_EVIDENCE = "REGISTRATION_EVIDENCE"
    CALIBRATION_EVIDENCE = "CALIBRATION_EVIDENCE"
    POLICY = "POLICY"
    INTERNAL = "INTERNAL"
