from __future__ import annotations

import re
import unicodedata
from datetime import datetime
from typing import Annotated, AsyncIterator

from fastapi import APIRouter, Depends, File, Form, Request, UploadFile, status
from pydantic import BaseModel, ValidationError, field_validator

from app.api.errors import ApiError, ApiErrorResponse
from app.db.models import ArtifactType, InspectionStatus
from app.services.artifact_storage import (
    ArtifactConflictError,
    ArtifactIntegrityError,
    ArtifactRegistrationError,
    ArtifactSizeLimitError,
    ArtifactStorageError,
    validate_intake_file,
)
from app.services.inspection_intake import (
    InspectionIntakeCommand,
    InspectionIntakeCoordinator,
    InspectionIntakeFailure,
    IntakeArtifactSource,
)

SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
MULTIPART_FIELDS = (
    "rgb_image",
    "height_map",
    "board_id",
    "recipe_id",
    "recipe_version",
    "lot_id",
    "operator_id",
    "station_id",
    "rgb_sha256",
    "height_sha256",
    "rgb_byte_size",
    "height_byte_size",
)


class _InspectionIntakeMetadata(BaseModel):
    board_id: str
    recipe_id: str
    recipe_version: str
    lot_id: str | None = None
    operator_id: str | None = None
    station_id: str | None = None
    rgb_sha256: str | None = None
    height_sha256: str | None = None
    rgb_byte_size: int | None = None
    height_byte_size: int | None = None

    @field_validator("board_id", "recipe_id", "recipe_version", mode="before")
    @classmethod
    def validate_required_identifier(cls, value: object) -> str:
        return cls._validated_identifier(value, required=True)

    @field_validator("lot_id", "operator_id", "station_id", mode="before")
    @classmethod
    def validate_optional_identifier(cls, value: object) -> str | None:
        return cls._validated_identifier(value, required=False)

    @staticmethod
    def _validated_identifier(value: object, *, required: bool) -> str | None:
        if not isinstance(value, str):
            raise ValueError("identifier must be text")
        if any(unicodedata.category(character) == "Cc" for character in value):
            raise ValueError("identifier must not contain control characters")
        normalized = value.strip()
        if not normalized:
            if required:
                raise ValueError("required identifier must not be empty")
            return None
        if len(normalized) > 128:
            raise ValueError("identifier must not exceed 128 characters")
        return normalized

    @field_validator("rgb_sha256", "height_sha256", mode="before")
    @classmethod
    def validate_expected_hash(cls, value: object) -> str | None:
        if value is None or value == "":
            return None
        if not isinstance(value, str) or not SHA256_PATTERN.fullmatch(value.strip()):
            raise ValueError("expected hash must be lowercase SHA-256")
        return value.strip()

    @field_validator("rgb_byte_size", "height_byte_size", mode="before")
    @classmethod
    def validate_expected_size(cls, value: object) -> int | None:
        if value is None or value == "":
            return None
        if isinstance(value, bool):
            raise ValueError("expected size must be a non-negative integer")
        text = str(value).strip()
        if not text.isdecimal():
            raise ValueError("expected size must be a non-negative integer")
        return int(text)


class IntakeArtifactResponse(BaseModel):
    artifact_type: ArtifactType
    sha256: str
    byte_size: int
    media_type: str | None


class InspectionIntakeResponse(BaseModel):
    inspection_id: str
    status: InspectionStatus
    board_id: str
    recipe_id: str
    recipe_version: str
    lot_id: str | None
    request_id: str
    created_at: datetime
    artifacts: list[IntakeArtifactResponse]


class _PairedUploads:
    def __init__(self, rgb_image: UploadFile, height_map: UploadFile) -> None:
        self.rgb_image = rgb_image
        self.height_map = height_map


async def _paired_uploads(
    rgb_image: Annotated[UploadFile, File(description="Original 2D RGB image")],
    height_map: Annotated[
        UploadFile,
        File(description="Original native height/depth raster or NumPy array"),
    ],
) -> AsyncIterator[_PairedUploads]:
    try:
        yield _PairedUploads(rgb_image, height_map)
    finally:
        await rgb_image.close()
        await height_map.close()


async def _reject_duplicate_fields(request: Request) -> None:
    form = await request.form()
    if form.getlist("inspection_id"):
        raise ApiError(
            status_code=400,
            code="CLIENT_INSPECTION_ID_NOT_ALLOWED",
            message="Inspection IDs are generated by the server.",
        )
    duplicates = [name for name in MULTIPART_FIELDS if len(form.getlist(name)) > 1]
    if duplicates:
        raise ApiError(
            status_code=400,
            code="DUPLICATE_MULTIPART_FIELD",
            message="Multipart fields must be supplied at most once.",
        )


def _map_intake_failure(failure: InspectionIntakeFailure) -> ApiError:
    cause = failure.cause
    if isinstance(cause, ArtifactSizeLimitError):
        return ApiError(413, "ARTIFACT_SIZE_LIMIT_EXCEEDED", "An artifact is too large.")
    if isinstance(cause, ArtifactConflictError):
        return ApiError(409, "IMMUTABLE_ARTIFACT_CONFLICT", "Artifact storage conflict.")
    if isinstance(cause, ArtifactIntegrityError):
        return ApiError(400, "ARTIFACT_INTEGRITY_MISMATCH", "Artifact integrity check failed.")
    if isinstance(cause, ArtifactRegistrationError):
        return ApiError(500, "ARTIFACT_REGISTRATION_FAILED", "Artifact registration failed.")
    if isinstance(cause, ArtifactStorageError):
        return ApiError(500, "ARTIFACT_STORAGE_FAILED", "Artifact storage failed.")
    return ApiError(500, "INSPECTION_INTAKE_FAILED", "Inspection intake failed.")


router = APIRouter(tags=["inspections"])


@router.post(
    "/inspections",
    response_model=InspectionIntakeResponse,
    status_code=status.HTTP_201_CREATED,
    responses={
        400: {"model": ApiErrorResponse},
        409: {"model": ApiErrorResponse},
        413: {"model": ApiErrorResponse},
        422: {"model": ApiErrorResponse},
        500: {"model": ApiErrorResponse},
    },
    summary="Receive one paired RGB and height-map inspection",
    description=(
        "Receives and immutably stores exactly one RGB file and one height/depth "
        "file for the same physical inspection instance. Files are not decoded or "
        "semantically validated, and alignment is not proven. RECEIVED does not "
        "mean PASS, FAIL, UNCERTAIN, ready for training, or production accepted."
    ),
)
async def create_inspection(
    request: Request,
    board_id: Annotated[str, Form(description="Board or assembly identifier")],
    recipe_id: Annotated[str, Form(description="Inspection recipe identifier")],
    recipe_version: Annotated[str, Form(description="Inspection recipe version")],
    uploads: Annotated[_PairedUploads, Depends(_paired_uploads)],
    lot_id: Annotated[str | None, Form()] = None,
    operator_id: Annotated[str | None, Form()] = None,
    station_id: Annotated[str | None, Form()] = None,
    rgb_sha256: Annotated[str | None, Form()] = None,
    height_sha256: Annotated[str | None, Form()] = None,
    rgb_byte_size: Annotated[str | None, Form()] = None,
    height_byte_size: Annotated[str | None, Form()] = None,
    _duplicates: Annotated[None, Depends(_reject_duplicate_fields)] = None,
) -> InspectionIntakeResponse:
    rgb_image = uploads.rgb_image
    height_map = uploads.height_map
    try:
        metadata = _InspectionIntakeMetadata(
            board_id=board_id,
            recipe_id=recipe_id,
            recipe_version=recipe_version,
            lot_id=lot_id,
            operator_id=operator_id,
            station_id=station_id,
            rgb_sha256=rgb_sha256,
            height_sha256=height_sha256,
            rgb_byte_size=rgb_byte_size,
            height_byte_size=height_byte_size,
        )
    except ValidationError as exc:
        raise ApiError(
            400,
            "INVALID_INTAKE_METADATA",
            "One or more intake metadata fields are invalid.",
        ) from exc

    try:
        validate_intake_file(
            ArtifactType.RGB_RAW,
            rgb_image.filename,
            rgb_image.content_type,
        )
        validate_intake_file(
            ArtifactType.HEIGHT_RAW,
            height_map.filename,
            height_map.content_type,
        )
    except ArtifactStorageError as exc:
        raise ApiError(
            400,
            "UNSUPPORTED_INTAKE_FORMAT",
            "An upload filename extension or media type is not accepted.",
        ) from exc

    coordinator: InspectionIntakeCoordinator = request.app.state.inspection_intake
    try:
        result = await coordinator.receive_pair(
            InspectionIntakeCommand(
                board_id=metadata.board_id,
                recipe_id=metadata.recipe_id,
                recipe_version=metadata.recipe_version,
                lot_id=metadata.lot_id,
                operator_id=metadata.operator_id,
                station_id=metadata.station_id,
                request_id=request.state.request_id,
                rgb=IntakeArtifactSource(
                    source=rgb_image.file,
                    original_filename=rgb_image.filename,
                    media_type=rgb_image.content_type,
                    expected_sha256=metadata.rgb_sha256,
                    expected_byte_size=metadata.rgb_byte_size,
                ),
                height=IntakeArtifactSource(
                    source=height_map.file,
                    original_filename=height_map.filename,
                    media_type=height_map.content_type,
                    expected_sha256=metadata.height_sha256,
                    expected_byte_size=metadata.height_byte_size,
                ),
            )
        )
    except InspectionIntakeFailure as exc:
        raise _map_intake_failure(exc) from exc

    inspection = result.inspection
    return InspectionIntakeResponse(
        inspection_id=inspection.id,
        status=inspection.status,
        board_id=inspection.board_id,
        recipe_id=inspection.recipe_id,
        recipe_version=inspection.recipe_version,
        lot_id=inspection.lot_id,
        request_id=inspection.request_id or request.state.request_id,
        created_at=inspection.created_at,
        artifacts=[
            IntakeArtifactResponse(
                artifact_type=artifact.artifact_type,
                sha256=artifact.sha256,
                byte_size=artifact.byte_size,
                media_type=artifact.media_type,
            )
            for artifact in result.artifacts
        ],
    )
